/**
 * TBL SITE DATA — nguồn dữ liệu duy nhất
 * ==========================================
 * Khi thêm bài mới: thêm 1 object vào mảng ARTICLES
 * Khi thêm series: thêm 1 object vào mảng SERIES
 * Khi thêm podcast: thêm 1 object vào mảng PODCAST
 * KHÔNG cần sửa file HTML nào khác.
 */

const TBL = {

  // ─── BRAND ──────────────────────────────────────────────────
  brand: {
    name: "The Becoming Learners",
    tagline: "by Vy Phan",
    byline: "EFL Educator · Doctoral Candidate in Education · Vietnam",
    youtube: "https://www.youtube.com/@TheBecomingLearners",
    linkedin: "https://www.linkedin.com/in/phan-vy-0b090234b/",
    portfolio: "https://phanvyedu.github.io/portfolio/",
    email: "thebecominglearners@gmail.com",
  },

  // ─── SERIES ─────────────────────────────────────────────────
  // Để thêm series mới: copy 1 object bên dưới, thay thông tin
  series: [
    {
      code: "LAI",
      name: "Learning & AI",
      fullName: "Learning in the Age of AI",
      color: "#854F0B",
      bg: "#FEF3E7",
      gradient: "linear-gradient(135deg,#FAC775 0%,#854F0B 100%)",
      desc: "AI is already in Vietnamese classrooms. This series doesn't ask whether to use it — it asks what happens to learning when we do. Every episode is anchored to a learning theory, not a tool list.",
      tags: ["Critical lens", "Vietnamese classroom", "Cognitive science", "Educator identity"],
      url: "series/lai.html",
      minPerEp: "15–18",
    },
    {
      code: "L5M",
      name: "Learning in 5 Minutes",
      fullName: "Learning in 5 Minutes",
      color: "#085041",
      bg: "#E1F5EE",
      gradient: "linear-gradient(135deg,#9FE1CB 0%,#1A5C5C 100%)",
      desc: "One concept from learning science. One actionable technique. Every episode ends with something you can try today — because knowing about learning isn't the same as doing it.",
      tags: ["Retrieval practice", "Spacing effect", "Cognitive load", "Actionable"],
      url: "series/l5m.html",
      minPerEp: "5–7",
    },
    {
      code: "TWC",
      name: "Thinkers Who Changed Ed.",
      fullName: "Thinkers Who Changed Education",
      color: "#712B13",
      bg: "#FAECE7",
      gradient: "linear-gradient(135deg,#F5C4B3 0%,#712B13 100%)",
      desc: "The ideas of Dewey, Vygotsky, Freire and others didn't stay in their century. This series traces how their thinking — and its limits — shows up in Vietnamese classrooms today.",
      tags: ["John Dewey", "Vygotsky", "Freire", "Educational philosophy"],
      url: "series/twc.html",
      minPerEp: "18–25",
    },
    {
      code: "BAL",
      name: "Becoming a Learner",
      fullName: "Becoming a Learner",
      color: "#3C3489",
      bg: "#EEEDFE",
      gradient: "linear-gradient(135deg,#AFA9EC 0%,#3C3489 100%)",
      desc: "After 15 years of teaching, the shift from teacher-identity to learner-identity changed everything. This series is personal — about what it actually means to keep learning when learning is your job.",
      tags: ["Personal reflection", "Learner identity", "Doctoral journey", "Growth mindset"],
      url: "series/bal.html",
      minPerEp: "12–15",
    },
  ],

  // ─── ARTICLES ───────────────────────────────────────────────
  // Để thêm bài mới: thêm object mới VÀO ĐẦU mảng (bài mới nhất lên trên)
  // published: true = bài đã đăng, false = coming soon
  articles: [
    {
      id: "BAL-01",
      series: "BAL",
      title: "Why I stopped calling myself a teacher",
      excerpt: "After fifteen years in Vietnamese classrooms, the label I had built my life around started to feel like a ceiling. This is the honest story of what changed.",
      date: "9 Jun 2026",
      lang: "EN",
      url: "articles/bal-01.html",
      published: true,
    },
    {
      id: "L5M-04",
      series: "L5M",
      title: "Interleaving: the counterintuitive practice that accelerates mastery",
      excerpt: "Blocked practice feels productive. Interleaving feels frustrating. The research is unambiguous about which one builds deeper, more flexible knowledge.",
      date: "6 May 2026",
      lang: "EN",
      url: "articles/l5m-04.html",
      published: true,
    },
    {
      id: "TWC-02",
      series: "TWC",
      title: "Vygotsky's Zone of Proximal Development — and what AI does to it",
      excerpt: "Vygotsky gave us the ZPD. AI can scaffold that gap. But entering the gap is not the same as opening it — and the difference matters enormously.",
      date: "2 Jun 2026",
      lang: "EN",
      url: "articles/twc-02.html",
      published: true,
    },
    {
      id: "TWC-01",
      series: "TWC",
      title: "John Dewey and the classroom that never arrived in Vietnam",
      excerpt: "Dewey argued that learning is experience. A century later, his most radical idea is still waiting at the door of the Vietnamese classroom.",
      date: "26 May 2026",
      lang: "EN",
      url: "articles/twc-01.html",
      published: true,
    },
    {
      id: "LAI-06",
      series: "LAI",
      title: "AI policy in Vietnamese education: what the guidelines say and what they miss",
      excerpt: "Vietnam has some of the most ambitious AI education policies in Southeast Asia. Ambition and implementation are different things.",
      date: "19 May 2026",
      lang: "EN",
      url: "articles/lai-06.html",
      published: true,
    },
    {
      id: "LAI-05",
      series: "LAI",
      title: "Who is the teacher when AI is in the room?",
      excerpt: "If AI can explain, scaffold, and give feedback — the question is no longer what teachers do. It is what teaching is for.",
      date: "12 May 2026",
      lang: "EN",
      url: "articles/lai-05.html",
      published: true,
    },
    {
      id: "L5M-03",
      series: "L5M",
      title: "Retrieval practice: why testing yourself works better than re-reading",
      excerpt: "Re-reading feels productive. It is not. The act of pulling information out of memory — before you feel ready — is what actually builds durable knowledge.",
      date: "29 Apr 2026",
      lang: "EN",
      url: "articles/l5m-03.html",
      published: true,
    },
    {
      id: "LAI-04",
      series: "LAI",
      title: "Shame, fear, and AI: what learner psychology tells us about adoption",
      excerpt: "Why some students rush toward AI tools while others quietly avoid them — and what both responses reveal about the psychology of learning itself.",
      date: "5 May 2026",
      lang: "EN",
      url: "articles/lai-04.html",
      published: true,
    },
    {
      id: "L5M-02",
      series: "L5M",
      title: "The spacing effect: one small habit that changes everything",
      excerpt: "Ebbinghaus mapped the forgetting curve 140 years ago. The fix has been known ever since. Here is why most students still do not use it.",
      date: "22 Apr 2026",
      lang: "EN",
      url: "articles/l5m-02.html",
      published: true,
    },
    {
      id: "LAI-03",
      series: "LAI",
      title: "The Confucian classroom meets the AI tutor",
      excerpt: "AI tutors were built on Western assumptions about learning. What happens when they enter a classroom shaped by two thousand years of very different values?",
      date: "28 Apr 2026",
      lang: "EN",
      url: "articles/lai-03.html",
      published: true,
    },
    {
      id: "LAI-02",
      series: "LAI",
      title: "What happens to English learning when AI can translate everything?",
      excerpt: "Krashen's i+1 formula worked when comprehensible input was scarce. Now that AI can remove all friction — what happens to acquisition?",
      date: "21 Apr 2026",
      lang: "EN",
      url: "articles/lai-02.html",
      published: true,
    },
    {
      id: "L5M-01",
      series: "L5M",
      title: "What does it actually mean to learn something?",
      excerpt: "Most studying stops at Exposure and calls itself done. Here's the three-stage model — and one technique to close the gap today.",
      date: "14 Apr 2026",
      lang: "EN",
      url: "articles/l5m-01.html",
      published: true,
    },
    {
      id: "LAI-01",
      series: "LAI",
      title: "Does AI make us better learners — or just faster forgetters?",
      excerpt: "When AI handles retrieval for us, what happens to the learning? A look at cognitive load theory, the generation effect, and what Vietnamese classrooms reveal.",
      date: "14 Apr 2026",
      lang: "EN",
      url: "articles/lai-01.html",
      published: true,
    },
  ],

  // ─── PODCAST ────────────────────────────────────────────────
  // Để thêm tập mới: thêm object mới VÀO ĐẦU mảng
  podcast: [
    {
      num: "03",
      title: "AI tutors and the illusion of understanding",
      titleVI: "AI gia sư và ảo giác \"hiểu bài\"",
      desc: "When an AI tutor explains something clearly, the student feels like they understand. But feeling like you understand and actually understanding are different things — and the gap between them is where learning either happens or doesn't.",
      duration: "34 min",
      lang: "EN",
      date: "Apr 2026",
      url: "https://www.youtube.com/@TheBecomingLearners",
      published: true,
    },
    {
      num: "02",
      title: "Confucian classrooms and constructivist theory",
      titleVI: "Lớp học Nho giáo và lý thuyết kiến tạo",
      desc: "What happens when educational theory built on Western assumptions meets the reality of a Vietnamese classroom? A conversation about Vygotsky, face-concern, and what participation actually means.",
      duration: "28 min",
      lang: "EN",
      date: "Mar 2026",
      url: "https://www.youtube.com/@TheBecomingLearners",
      published: true,
    },
    {
      num: "01",
      title: "Why I study learning after 15 years of teaching",
      titleVI: "Tại sao tôi nghiên cứu học tập sau 15 năm dạy",
      desc: "The question that started this channel: if I have been teaching for fifteen years, why do I know so little about how people actually learn?",
      duration: "22 min",
      lang: "EN · VI",
      date: "Mar 2026",
      url: "https://www.youtube.com/@TheBecomingLearners",
      published: true,
    },
  ],

};
